name: Django Deployment
on:
  push:
    branches:
      - main 
jobs: 
  build: 
    runs-on: ubuntu-latest  
   
    services:
         postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: Survey1
          ports: 
            - 5432:5432
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          python -m pip install Django
          python -m pip install  psycopg2
         
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install
          sudo apt-get install -y postgresql
          sudo service postgresql start
          sudo service postgresql status
            
           
      - name: Activate Virtual env
        run: |
          source world/Scripts/activate

        
          
      - name: Run database migrations
        run: |
          cd project_survey
          python manage.py makemigrations
          python manage.py migrate
      - name: Collect static files
        run: |
          cd project_survey
          python manage.py collectstatic --noinput
      - name: Install Gunicorn
        run: |
          python -m pip install gunicorn
      - name: Run Django application using Gunicorn
        run: |
          cd project_survey
          gunicorn project_survey.wsgi:application
          
                 
